server:
  port: 8080
spring:
  jpa:
     hibernate:
       ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root123
    password: root
    url: jdbc:mysql://localhost:3306/carwashTT?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC